Control de exit codes
El exito code que devuelve el script cuando es lanzado desde xterm se
guarda en el script principal para saber si debe continuar o no

diff --git a/Auditoria/openvas-manager_updater b/Auditoria/openvas-manager_updater
--- a/Auditoria/openvas-manager_updater
+++ b/Auditoria/openvas-manager_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20150829
+SCRIPT_VERSION=20150830
 
 ############################################################
 ## Funciones comunes. Su nombre empieza por f_ ##
@@ -47,7 +47,22 @@ F_dependencias(){
 		echo ""
 		echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
 		sleep 3
-		cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/openvas-libraries_updater && cd $TMP
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/openvas-libraries_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
 	fi
 
 	echo ""
diff --git a/Auditoria/openvas-scanner_updater b/Auditoria/openvas-scanner_updater
--- a/Auditoria/openvas-scanner_updater
+++ b/Auditoria/openvas-scanner_updater
@@ -47,7 +47,21 @@ F_dependencias(){
 		echo ""
 		echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
 		sleep 3
-		cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/openvas-libraries_updater && cd $TMP
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/openvas-libraries_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
 	fi
 
 	echo ""
diff --git a/Internet/filezilla_updater b/Internet/filezilla_updater
--- a/Internet/filezilla_updater
+++ b/Internet/filezilla_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20150825
+SCRIPT_VERSION=20150829
 
 ############################################################
 ## Funciones comunes. Su nombre empieza por f_ ##
@@ -40,24 +40,38 @@ sleep 3
 	echo "$AMARILLO"wxGTK3"$CIERRE: $EXIST"
 	DEPENDENCIA=`ps -A | grep -o wxGTK3_updat`
 	if [ ! $DEPENDENCIA = "" ]; then
-	echo ""
-	echo ""$ROJO"Se ha detectado en funcionamiento el "$AMARILLO"wxPython_updater"$CIERRE"..."
-	echo ""
-	echo ""$ROJO"Cuando acabe dicho updater lanza de nuevo este"$CIERRE"..."
-	echo ""
-	exit 1
+		echo ""
+		echo ""$ROJO"Se ha detectado en funcionamiento el "$AMARILLO"wxPython_updater"$CIERRE"..."
+		echo ""
+		echo ""$ROJO"Cuando acabe dicho updater lanza de nuevo este"$CIERRE"..."
+		echo ""
+		exit 1
 	fi
 	if [ ! -f /usr/lib/wx/config/gtk2-unicode-3.0 ]; then
-	echo ""
-	echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
-	sleep 3
-	cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/wxGTK3_updater && cd $TMP
-else
-	echo ""
-	echo "$VERDE"Bien ..podemos continuar"$CIERRE"
-	echo ""
-sleep 3
-fi
+		echo ""
+		echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
+		sleep 3
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/wxGTK3_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
+	else
+		echo ""
+		echo "$VERDE"Bien ..podemos continuar"$CIERRE"
+		echo ""
+		sleep 3
+	fi
 }
 
 
diff --git a/Juegos/gnome-sudoku_updater b/Juegos/gnome-sudoku_updater
--- a/Juegos/gnome-sudoku_updater
+++ b/Juegos/gnome-sudoku_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20150725
+SCRIPT_VERSION=20150829
 
 ############################################################
 ## Funciones comunes. Su nombre empieza por f_ ##
@@ -26,96 +26,126 @@ F_variables() {
 }
 
 F_dependencias(){
-if [ -f /usr/lib/pkgconfig/gee-0.8.pc ]; then
-LIBGEE_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
-LIBGEE_EXIST2=SI
-else
-LIBGEE_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
-LIBGEE_EXIST2=NO
-fi
-if [ -f /usr/bin/qqwing ]; then
-QQWING_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
-QQWING_EXIST2=SI
-else
-QQWING_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
-QQWING_EXIST2=NO
-fi
+	if [ -f /usr/lib/pkgconfig/gee-0.8.pc ]; then
+		LIBGEE_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
+		LIBGEE_EXIST2=SI
+	else
+		LIBGEE_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
+		LIBGEE_EXIST2=NO
+	fi
+	
+	if [ -f /usr/bin/qqwing ]; then
+		QQWING_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
+		QQWING_EXIST2=SI
+	else
+		QQWING_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
+		QQWING_EXIST2=NO
+	fi
 
-echo "$ROSA"Comprobando dependencias ..."$CIERRE"
-echo
-sleep 3
-echo "$CYAN"Dependencias de este paquete:""
-echo ""
-echo "$AMARILLO"libgee"$CIERRE: $LIBGEE_EXIST"
-if [ $LIBGEE_EXIST2 = NO ]; then
-echo "$AMARILLO"
-echo "Resolviendo dependencia libgee ..."
-sleep 3
-if [ ! -f /opt/wifislax-updaters/Librerias/libgee_updater ]; then
-echo $ROJO
-echo "No tienes el updater libgee..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
-cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/libgee_updater && cd $TMP
-fi
+	echo "$ROSA"Comprobando dependencias ..."$CIERRE"
+	echo
+	sleep 3
+	echo "$CYAN"Dependencias de este paquete:""
+	echo ""
+	echo "$AMARILLO"libgee"$CIERRE: $LIBGEE_EXIST"
+	
+	if [ $LIBGEE_EXIST2 = NO ]; then
+		echo "$AMARILLO"
+		echo "Resolviendo dependencia libgee ..."
+		sleep 3
+		if [ ! -f /opt/wifislax-updaters/Librerias/libgee_updater ]; then
+			echo $ROJO
+			echo "No tienes el updater libgee..."
+			sleep 1
+			echo "No se puede continuar..."
+			sleep 1
+			echo "El script se cierra aqui."
+			sleep 1
+			echo $CIERRE
+			exit 0
+		fi
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/libgee_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
+	fi
 
-# Verificamos que salio bien libgee_updater
-if [ ! -f /usr/lib/pkgconfig/gee-0.8.pc ]; then
-echo $ROJO
-echo "Algo salio mal al instalar libgee..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi 
+	# Verificamos que salio bien libgee_updater
+	if [ ! -f /usr/lib/pkgconfig/gee-0.8.pc ]; then
+		echo $ROJO
+		echo "Algo salio mal al instalar libgee..."
+		sleep 1
+		echo "No se puede continuar..."
+		sleep 1
+		echo "El script se cierra aqui."
+		sleep 1
+		echo $CIERRE
+		exit 0
+	fi 
 
-echo "$AMARILLO"qqwing"$CIERRE: $QQWING_EXIST"
-if [ $QQWING_EXIST2 = NO ]; then
-echo "$AMARILLO"
-echo "Resolviendo dependencia qqwing ..."
-sleep 3
-if [ ! -f /opt/wifislax-updaters/Librerias/qqwing_updater ]; then
-echo $ROJO
-echo "No tienes el updater qqwing..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
-cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/qqwing_updater && cd $TMP
-fi
+	echo "$AMARILLO"qqwing"$CIERRE: $QQWING_EXIST"
+	if [ $QQWING_EXIST2 = NO ]; then
+		echo "$AMARILLO"
+		echo "Resolviendo dependencia qqwing ..."
+		sleep 3
+		if [ ! -f /opt/wifislax-updaters/Librerias/qqwing_updater ]; then
+			echo $ROJO
+			echo "No tienes el updater qqwing..."
+			sleep 1
+			echo "No se puede continuar..."
+			sleep 1
+			echo "El script se cierra aqui."
+			sleep 1
+			echo $CIERRE
+			exit 0
+		fi
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/qqwing_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
+	fi
 
-# Verificamos que salio bien qqwing_updater
-if [ ! -f /usr/bin/qqwing ]; then
-echo $ROJO
-echo "Algo salio mal al instalar qqwing..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi 
+	# Verificamos que salio bien qqwing_updater
+	if [ ! -f /usr/bin/qqwing ]; then
+		echo $ROJO
+		echo "Algo salio mal al instalar qqwing..."
+		sleep 1
+		echo "No se puede continuar..."
+		sleep 1
+		echo "El script se cierra aqui."
+		sleep 1
+		echo $CIERRE
+		exit 0
+	fi 
 
 
-# Si todo salio bien
-echo ""
-echo "$VERDE"Bien ..podemos continuar"$CIERRE"
-echo ""
-sleep 3
+	# Si todo salio bien
+	echo ""
+	echo "$VERDE"Bien ..podemos continuar"$CIERRE"
+	echo ""
+	sleep 3
 }
 
 # Si el paquete no existe se descargara de internet
diff --git a/Multimedia/aegisub_updater b/Multimedia/aegisub_updater
--- a/Multimedia/aegisub_updater
+++ b/Multimedia/aegisub_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20150729
+SCRIPT_VERSION=20150829
 CATEGORIA="Editores de video"
 
 ############################################################
@@ -26,56 +26,71 @@ F_variables() {
 }
 
 F_dependencias(){
-if [ -f /usr/bin/ffmsindex ]; then
-FFMS2_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
-FFMS2_EXIST2=SI
-else
-FFMS2_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
-FFMS2_EXIST2=NO
-fi
+	if [ -f /usr/bin/ffmsindex ]; then
+		FFMS2_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
+		FFMS2_EXIST2=SI
+	else
+		FFMS2_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
+		FFMS2_EXIST2=NO
+	fi
 
-echo "$ROSA"Comprobando dependencias ..."$CIERRE"
-echo
-sleep 3
-echo "$CYAN"Dependencias de este paquete:""
-echo ""
-echo "$AMARILLO"ffms2"$CIERRE: $FFMS2_EXIST"
-if [ $FFMS2_EXIST2 = NO ]; then
-echo "$AMARILLO"
-echo "Resolviendo dependencia ffms2 ..."
-sleep 3
-if [ ! -f /opt/wifislax-updaters/Librerias/ffms2_updater ]; then
-echo $ROJO
-echo "No tienes el updater ffms2..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
-cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/ffms2_updater && cd $TMP
-fi
+	echo "$ROSA"Comprobando dependencias ..."$CIERRE"
+	echo
+	sleep 3
+	echo "$CYAN"Dependencias de este paquete:""
+	echo ""
+	echo "$AMARILLO"ffms2"$CIERRE: $FFMS2_EXIST"
+	
+	if [ $FFMS2_EXIST2 = NO ]; then
+		echo "$AMARILLO"
+		echo "Resolviendo dependencia ffms2 ..."
+		sleep 3
+		if [ ! -f /opt/wifislax-updaters/Librerias/ffms2_updater ]; then
+			echo $ROJO
+			echo "No tienes el updater ffms2..."
+			sleep 1
+			echo "No se puede continuar..."
+			sleep 1
+			echo "El script se cierra aqui."
+			sleep 1
+			echo $CIERRE
+			exit 0
+		fi
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/ffms2_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
+	fi
 
-# Verificamos que salio bien ffms2_updater
-if [ ! -f /usr/bin/ffmsindex ]; then
-echo $ROJO
-echo "Algo salio mal al instalar ffms2..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
+	# Verificamos que salio bien ffms2_updater
+	if [ ! -f /usr/bin/ffmsindex ]; then
+		echo $ROJO
+		echo "Algo salio mal al instalar ffms2..."
+		sleep 1
+		echo "No se puede continuar..."
+		sleep 1
+		echo "El script se cierra aqui."
+		sleep 1
+		echo $CIERRE
+		exit 0
+	fi
 
-# Si todo salio bien
-echo ""
-echo "$VERDE"Bien ..podemos continuar"$CIERRE"
-echo ""
-sleep 3
+	# Si todo salio bien
+	echo ""
+	echo "$VERDE"Bien ..podemos continuar"$CIERRE"
+	echo ""
+	sleep 3
 }
 
 # Si el paquete no existe se descargara de internet
diff --git a/Multimedia/ardour_updater b/Multimedia/ardour_updater
--- a/Multimedia/ardour_updater
+++ b/Multimedia/ardour_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20150802
+SCRIPT_VERSION=20150829
 CATEGORIA="Editores de audio"
 
 ############################################################
@@ -29,129 +29,175 @@ F_variables() {
 # Comprobar dependencias
 F_dependencias(){
 #1
-if [ -f /usr/bin/dot ] ;then
-GRAPHVIZ_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
-GRAPHVIZ_EXIST2=SI
-else
-GRAPHVIZ_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
-GRAPHVIZ_EXIST2=NO
-fi
-echo "$ROSA"Comprobando dependencias ..."$CIERRE"
-echo
-sleep 3
-echo "$CYAN"Dependencias de este paquete:""
-echo ""
-echo "$AMARILLO"graphviz"$CIERRE: $GRAPHVIZ_EXIST"
-if [ $GRAPHVIZ_EXIST2 = NO ]; then
-echo "$AMARILLO"
-echo "Resolviendo dependencia graphviz ..."
-sleep 3
-if [ ! -f /opt/wifislax-updaters/Librerias/graphviz_updater ]; then
-echo $ROJO
-echo "No tienes el updater graphviz..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
-cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/graphviz_updater && cd $TMP
-fi
+	if [ -f /usr/bin/dot ] ;then
+		GRAPHVIZ_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
+		GRAPHVIZ_EXIST2=SI
+	else
+		GRAPHVIZ_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
+		GRAPHVIZ_EXIST2=NO
+	fi
+	
+	echo "$ROSA"Comprobando dependencias ..."$CIERRE"
+	echo
+	sleep 3
+	echo "$CYAN"Dependencias de este paquete:""
+	echo ""
+	echo "$AMARILLO"graphviz"$CIERRE: $GRAPHVIZ_EXIST"
+	
+	if [ $GRAPHVIZ_EXIST2 = NO ]; then
+		echo "$AMARILLO"
+		echo "Resolviendo dependencia graphviz ..."
+		sleep 3
+		if [ ! -f /opt/wifislax-updaters/Librerias/graphviz_updater ]; then
+			echo $ROJO
+			echo "No tienes el updater graphviz..."
+			sleep 1
+			echo "No se puede continuar..."
+			sleep 1
+			echo "El script se cierra aqui."
+			sleep 1
+			echo $CIERRE
+			exit 0
+		fi
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/graphviz_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
+	fi
 
-# Verificamos que salio bien graphviz_updater
-if [ ! -f /usr/bin/dot ] ;then
-echo $ROJO
-echo "Algo salio mal al instalar graphviz..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
+	# Verificamos que salio bien graphviz_updater
+	if [ ! -f /usr/bin/dot ] ;then
+		echo $ROJO
+		echo "Algo salio mal al instalar graphviz..."
+		sleep 1
+		echo "No se puede continuar..."
+		sleep 1
+		echo "El script se cierra aqui."
+		sleep 1
+		echo $CIERRE
+		exit 0
+	fi
 
 #2
-if [ -f /usr/lib/pkgconfig/lrdf.pc ];then
-LIBLRDF_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
-LIBLRDF_EXIST2=SI
-else
-LIBLRDF_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
-LIBLRDF_EXIST2=NO
-fi
-echo "$AMARILLO"liblrdf"$CIERRE: $LIBLRDF_EXIST"
-if [ $LIBLRDF_EXIST2 = NO ]; then
-echo "$AMARILLO"
-echo "Resolviendo dependencia liblrdf ..."
-sleep 3
-if [ ! -f /opt/wifislax-updaters/Librerias/liblrdf_updater ]; then
-echo $ROJO
-echo "No tienes el updater liblrdf..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
-cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/liblrdf_updater && cd $TMP
-fi
+	if [ -f /usr/lib/pkgconfig/lrdf.pc ];then
+		LIBLRDF_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
+		LIBLRDF_EXIST2=SI
+	else
+		LIBLRDF_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
+		LIBLRDF_EXIST2=NO
+	fi
+	
+	echo "$AMARILLO"liblrdf"$CIERRE: $LIBLRDF_EXIST"
+	if [ $LIBLRDF_EXIST2 = NO ]; then
+		echo "$AMARILLO"
+		echo "Resolviendo dependencia liblrdf ..."
+		sleep 3
+		if [ ! -f /opt/wifislax-updaters/Librerias/liblrdf_updater ]; then
+			echo $ROJO
+			echo "No tienes el updater liblrdf..."
+			sleep 1
+			echo "No se puede continuar..."
+			sleep 1
+			echo "El script se cierra aqui."
+			sleep 1
+			echo $CIERRE
+			exit 0
+		fi
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/liblrdf_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
+	fi
 
-# Verificamos que salio bien liblrdf_updater
-if [ ! -f /usr/lib/pkgconfig/lrdf.pc ];then
-echo $ROJO
-echo "Algo salio mal al instalar liblrdf..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
+	# Verificamos que salio bien liblrdf_updater
+	if [ ! -f /usr/lib/pkgconfig/lrdf.pc ];then
+		echo $ROJO
+		echo "Algo salio mal al instalar liblrdf..."
+		sleep 1
+		echo "No se puede continuar..."
+		sleep 1
+		echo "El script se cierra aqui."
+		sleep 1
+		echo $CIERRE
+		exit 0
+	fi
 
 #3
-if [ -f /usr/bin/aubiocut ];then
-AUBIO_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
-AUBIO_EXIST2=SI
-else
-AUBIO_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
-AUBIO_EXIST2=NO
-fi
-echo "$AMARILLO"aubio"$CIERRE: $AUBIO_EXIST"
-if [ $AUBIO_EXIST2 = NO ]; then
-echo "$AMARILLO"
-echo "Resolviendo dependencia aubio ..."
-sleep 3
-if [ ! -f /opt/wifislax-updaters/Librerias/aubio_updater ]; then
-echo $ROJO
-echo "No tienes el updater aubio..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
-cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/aubio_updater && cd $TMP
-fi
+	if [ -f /usr/bin/aubiocut ];then
+		AUBIO_EXIST=`echo "$VERDE"Instalada"$CIERRE"`
+		AUBIO_EXIST2=SI
+	else
+		AUBIO_EXIST=`echo "$ROJO"No Instalada"$CIERRE"`
+		AUBIO_EXIST2=NO
+	fi
+	
+	echo "$AMARILLO"aubio"$CIERRE: $AUBIO_EXIST"
+	if [ $AUBIO_EXIST2 = NO ]; then
+		echo "$AMARILLO"
+		echo "Resolviendo dependencia aubio ..."
+		sleep 3
+		if [ ! -f /opt/wifislax-updaters/Librerias/aubio_updater ]; then
+			echo $ROJO
+			echo "No tienes el updater aubio..."
+			sleep 1
+			echo "No se puede continuar..."
+			sleep 1
+			echo "El script se cierra aqui."
+			sleep 1
+			echo $CIERRE
+			exit 0
+		fi
+		cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/aubio_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
+	fi
 
-# Verificamos que salio bien aubio_updater
-if [ ! -f /usr/bin/aubiocut ];then
-echo $ROJO
-echo "Algo salio mal al instalar aubio..."
-sleep 1
-echo "No se puede continuar..."
-sleep 1
-echo "El script se cierra aqui."
-sleep 1
-echo $CIERRE
-exit 0
-fi
+	# Verificamos que salio bien aubio_updater
+	if [ ! -f /usr/bin/aubiocut ];then
+		echo $ROJO
+		echo "Algo salio mal al instalar aubio..."
+		sleep 1
+		echo "No se puede continuar..."
+		sleep 1
+		echo "El script se cierra aqui."
+		sleep 1
+		echo $CIERRE
+		exit 0
+	fi
 }
 
 # Si el paquete no existe se descargara de internet
diff --git a/Multimedia/audacity_updater b/Multimedia/audacity_updater
--- a/Multimedia/audacity_updater
+++ b/Multimedia/audacity_updater
@@ -2,7 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20150704
+SCRIPT_VERSION=20150829
 CATEGORIA="Editores de audio"
 
 ############################################################
@@ -51,7 +51,21 @@ sleep 3
 	echo ""
 	echo ""$ROJO"No se cumplen los requisitos"$CIERRE"... "$VERDE"resolviendo"$CIERRE"..."
 	sleep 3
-	cd /opt/wifislax-updaters/Librerias/ && xterm /opt/wifislax-updaters/Librerias/wxPython_updater && cd $TMP
+	cd /opt/wifislax-updaters/Librerias/
+		statusfile=$(mktemp)
+		xterm -e sh -c '/opt/wifislax-updaters/Librerias/wxPython_updater; echo $? > '$statusfile 
+		status=$(cat $statusfile)
+		rm $statusfile
+		if [ -z $status ] || [ $status != "0" ]; then
+		  echo "$ROJO"ERROR. No se ha podido crear el paquete"$CIERRE"
+		  if [ -z $status ]; then
+		    exit 1
+		  else
+		    exit $status
+		  fi
+		fi
+		
+		cd $TMP
 else
 	echo ""
 	echo "$VERDE"Bien ..podemos continuar"$CIERRE"
