Nuevas dependencias ardour

diff --git a/Librerias-Audio/ladspa_sdk_updater b/Librerias-Audio/ladspa_sdk_updater
--- a/Librerias-Audio/ladspa_sdk_updater
+++ b/Librerias-Audio/ladspa_sdk_updater
@@ -2,8 +2,7 @@
 
 # Script by www.seguridadwireless.net
 
-SCRIPT_VERSION=20160402
-CATEGORIA="Editores de audio"
+SCRIPT_VERSION=20160403
 
 ############################################################
 ## Funciones comunes. Su nombre empieza por f_ ##
@@ -17,60 +16,47 @@ f_variables(){
 ############################################################
 # Definicion de variables
 F_variables() {
-	PRGNAM=ardour
+	PRGNAM=ladspa_sdk
 	echo -ne "\033]2;${PRGNAM}_updater\007"
-	WEB=https://github.com/Ardour/${PRGNAM}
-	VERSION=`curl -s $WEB/releases|grep tar.gz|head -1|cut -d t -f1|cut -d / -f5|sed "s/.$//g"`
-	RAMA=`echo $VERSION | cut -d . -f1`
-	WEB=git://git.ardour.org/ardour/ardour.git
-}
-
-# Comprobar dependencias
-F_dependencias(){
-DEPENDENCIAS="aubio jack-audio-connection-kit liblo liblrdf vamp-plugin-sdk rubberband"
-f_dependencias
-}
-
-# Git clone
-F_download(){
-if [ -d $TMP/$PRGNAM ]; then
-rm -rf $TMP/$PRGNAM
-fi
-echo ""
-echo "$VERDE"Descargando sources de ${AMARILLO}$PRGNAM-$VERSION${BLANCO}..."$CIERRE"
-sleep 1
-cd $TMP
-git clone $WEB
-cd $TMP/$PRGNAM
+	WEB=http://pkgs.fedoraproject.org/repo/pkgs/ladspa
+	VERSION=1.13
+	EXTENSION=tgz
+	SRCNAM=${PRGNAM}_${VERSION}
+	SOURCES=$SRCNAM.$EXTENSION
+	DOWNLOAD=$WEB/$SOURCES/671be3e1021d0722cadc7fb27054628e/$SOURCES
 }
 
 # Descomprimimos el fichero descargado y compilamos
 F_compilar(){
-python2 waf configure \
-  --prefix=/usr \
-  --configdir=/etc \
-  --with-backends="jack,alsa" \
-  --libjack=weak \
-  --optimize \
-  --docs \
-  --cxx11 \
-  --no-phone-home
+echo 
+echo "$VERDE"Compilando ..."$CIERRE"
+sleep 1
 
-python2 waf build
+cd src
+  make \
+    CFLAGS="$SLKCFLAGS -I. -Wall -Werror -fPIC" \
+    INSTALL_PLUGINS_DIR="/usr/lib${LIBDIRSUFFIX}/ladspa" \
+    INSTALL_BINARY_DIR="/usr/bin"
 
-python2 waf install --destdir=$PKG
-  
-# Entrada a menu
-mkdir -p $PKG/usr/share/applications
-echo "[Desktop Entry]
-Name=Ardour $RAMA
-Comment=Multitrack hard disk recorder
-Exec=ardour$RAMA
-Icon=/usr/share/ardour$RAMA/icons/ardour_icon_256px.png
-Terminal=false
-Type=Application
-X-MultipleArgs=false
-Categories=Audio;AudioVideoEditing;AudioVideo;Video;" > $PKG/usr/share/applications/$PRGNAM.desktop
+  make install \
+    INSTALL_PLUGINS_DIR="$PKG/usr/lib${LIBDIRSUFFIX}/ladspa" \
+    INSTALL_BINARY_DIR="$PKG/usr/bin" \
+    INSTALL_INCLUDE_DIR="$PKG/usr/include"
+cd -
+
+mkdir -p $PKG/etc/profile.d/
+cat << EOF > $PKG/etc/profile.d/ladspa.csh
+#!/bin/csh
+setenv LADSPA_PATH /usr/lib${LIBDIRSUFFIX}/ladspa
+EOF
+cat << EOF > $PKG/etc/profile.d/ladspa.sh
+#!/bin/sh
+export LADSPA_PATH=/usr/lib${LIBDIRSUFFIX}/ladspa
+EOF
+chmod 0755 $PKG/etc/profile.d/*
+
+# Cleanup files left in /tmp by make
+rm -f /tmp/test.wav || true
 }
 
 ###################################
@@ -81,6 +67,8 @@ trap f_exitmode SIGHUP SIGINT
 
 #Inicializamos las variables globales
 f_variables
+#Asignamos o detectamos arquitectura
+f_arquitectura
 #Comprobamos conexion a Internet
 f_comprobarConexion
 #Inicializamos las variables del script
@@ -91,14 +79,12 @@ f_directorioTemporal
 f_presentacion
 #Comprobamos updates del script
 f_comprobarUpdates
-#Asignamos o detectamos arquitectura
-f_arquitectura
 #Comprobamos version instalada del paquete
 f_versionInstalada
-#Compronar dependencias
-F_dependencias
-# Git clone
-F_download
+#Si no existe el fichero se descargara
+f_download
+#Preparamos entorno
+f_preparar
 #Descomprimir fichero descargado y compilamos
 F_compilar
 #Hacemos strip sobre el paquete
